

# This file was *autogenerated* from the file attack_gcd.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_30 = Integer(30); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_90178679 = Integer(90178679); _sage_const_25165034 = Integer(25165034); _sage_const_222298938 = Integer(222298938); _sage_const_618 = Integer(618); _sage_const_116392301 = Integer(116392301); _sage_const_135267368 = Integer(135267368); _sage_const_358615007 = Integer(358615007); _sage_const_36699982 = Integer(36699982); _sage_const_376442052 = Integer(376442052); _sage_const_69206973 = Integer(69206973); _sage_const_556 = Integer(556); _sage_const_190842532 = Integer(190842532); _sage_const_419433191 = Integer(419433191); _sage_const_503319187 = Integer(503319187); _sage_const_415238963 = Integer(415238963)
def remove_fatores_pequenos (a, num_fact =_sage_const_1000 ):
    q = _sage_const_2 
    for _ in range(num_fact):
        while q.divides(a):
            a /= q
        q = next_prime (q)
    return ZZ(a)

def ataque_por_mdc (gamma , eta , rho , list_samples ):
    x0 = list_samples [_sage_const_0 ]
    mult_p = prod ([x0 - r for r in range(-_sage_const_2 **rho , _sage_const_2 ** rho)])
    mult_p = remove_fatores_pequenos (mult_p) # mult. de p

    for i in range(_sage_const_1 , len( list_samples )):
        xi = list_samples [i]
        mi = prod ([xi - r for r in range(-_sage_const_2 **rho , _sage_const_2 ** rho )])
        mult_p = gcd(mult_p , mi) # máximo divisor comum
        print("bitlen mult_p = %d" % mult_p.nbits ())
        if eta >= log(mult_p , _sage_const_2 ) >= eta-_sage_const_1 :
            break
    return mult_p

print(ataque_por_mdc(_sage_const_30 ,_sage_const_20 ,_sage_const_10 ,[_sage_const_90178679 , _sage_const_25165034 , _sage_const_222298938 , _sage_const_618 , _sage_const_116392301 , _sage_const_135267368 , _sage_const_358615007 , _sage_const_36699982 , 
                    _sage_const_376442052 , _sage_const_69206973 , _sage_const_556 , _sage_const_190842532 , _sage_const_419433191 , _sage_const_503319187 , _sage_const_415238963 ]))


