

# This file was *autogenerated* from the file distribution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_15 = Integer(15); _sage_const_30 = Integer(30); _sage_const_1048583 = Integer(1048583); _sage_const_10 = Integer(10)
def sample_r(rho):
    return ZZ.random_element(-_sage_const_2 **rho, _sage_const_2 **rho)

def sample_q(gamma, eta):
    return ZZ.random_element(_sage_const_0 ,_sage_const_2 **(gamma-eta))

def sample_agcd(gamma, p, rho):
    eta = ceil(log(p, _sage_const_2 ))
    r = sample_r(rho)
    q = sample_q(gamma , eta)
    return p*q + r

L = []
for i in range(_sage_const_15 ):
    L.append(sample_agcd(_sage_const_30 , _sage_const_1048583 , _sage_const_10 ))

print(L)



